{"name": "Eсли авторизоваться под несуществующим пользователем, запрос возвращает ошибку :/api/v1/courier/login", "status": "passed", "start": 1725383039336, "stop": 1725383039527, "uuid": "6a2132dd-adaa-425e-8857-432a85ea154f", "historyId": "889ead25a56c85eb448c630e33abf422", "testCaseId": "889ead25a56c85eb448c630e33abf422", "fullName": "test.test_login_courier.TestLoginCourier#test_log_in_under_a_non_existent_user", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "Gansalles"}, {"name": "thread", "value": "13096-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_login_courier"}]}